### ISSUE TITLE
render issue with Hiyori (free) model

### ISSUE THREAD

**Issue by wryk** [Live2D/CubismJsComponents#1] opened 2017-08-31 12:30 UTC
I adapted your exemple with another model but I ran into a bug.
Preview in Cubism3 (latest version) is fine but with LIVE2DCUBISMPIXI I got a awkward render issue with Hiyori's iris :

![test](https://user-images.githubusercontent.com/1964408/29922499-2f3e73c4-8e56-11e7-8978-36a75359f74b.gif)

Model is Hiyori (free) from [live2d documentation](http://docs.live2d.com/en/cubism-editor-manual/sample-model/).

If you want I can host my test on github and provide a page for preview.
I think Hiyori license allow me to do that. (?)

**Comment by andi-at-live2d-com** [comment] 2017-09-01 00:39
@wryk Thanks for giving the SDK a try! Sorry, but the awkwardness arises from the fact that clipping masks aren't implemented yet... (-_-);
I added it as a TODO to the bottom of the [readme](https://github.com/Live2D/CubismJsComponents/blob/master/README.md), but let's keep this issue open until clipping is implemented.

> If you want I can host my test on github and provide a page for preview.
> I think Hiyori license allow me to do that. (?)

Right, license wise there shouldn't be any problems. This time the issue is pretty easy to reproduce, but it would be cool if you could host a preview next time. Very much appreciated!

**Comment by wryk** [comment] 2017-09-01 12:53
Sorry, my bad. I didn't put enough attention in the readme. :/
Okay, I'll do that next time !

**Comment by shiozawa-at-live2d-com** [comment] 2017-11-07 08:45
@wryk We are sorry to have kept you waiting.
We have implemented a clipping mask function.
It's already merged into the master branch so you can use it now.
Please check this example page, and the Mark-Kun's eye-blink is displayed correctly.
https://live2d.github.io/CubismJsComponents/

![eyeblink_clipping](https://user-images.githubusercontent.com/31648800/32484347-c8241104-c3e2-11e7-9bfa-76f80020d062.gif)

**Closed by shiozawa-at-live2d-com** 2017-11-07 08:45 UTC

**Comment by wryk** [comment] 2017-11-08 15:35
I updated my test (https://wryk.github.io/cubism-js-components-test/) with your latest changes and everything works great, thanks you !

**Comment by shiozawa-at-live2d-com** [comment] 2017-11-09 01:20
@wryk Thank you for your feedback!!
